FROM ghcr.io/open-webui/open-webui@sha256:c1e4beee0a16801816c878f7ac1d6c19cb8a52dc4655f540e8852909c782ffa1

USER root

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libreoffice-core \
        libreoffice-writer \
        libreoffice-calc \
        libreoffice-impress && \
    rm -rf /var/lib/apt/lists/*
